<%@ Page Title="Example" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Example.aspx.cs" Inherits="habit.Example" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">


    <div class="container body-content">
        <h3>This is a example of what the page looks like for a logged in user</h3>
        <p>Click here to create a user: <a href="/createuser.aspx">Create User</a></p>
          <p>Click here to login: <a href="/login.aspx">Login</a></p>
        <div id="rectangles_wrap">
            <div>
                <h1>
                    <br>
                </h1>
                <h4>
                    <div id="startdatetext" style="display: none;">Enter the date you started you new habit and click "Start!"</div>
                    <input type="text" id="datepicker" style="cursor: pointer; background-color: #f0ece3; border: 0px; width: 130px;" title="Click here to change date" class="hasDatepicker">
                    <a id="startdatesubmit" style="display: none;" href="#">Start!</a>
                </h4>
                <div id="rectangles" style="">
                    <span class="individualRectangle individualRectangle0 individualRectangleMinutes15" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle1 individualRectangleMinutes30" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle2 individualRectangleMinutes45" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle3 individualRectangleMinutes60" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle4 individualRectangleMinutes75" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle5 individualRectangleMinutes90" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle6 individualRectangleMinutes105" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle7 individualRectangleMinutes120" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle8 individualRectangleMinutes135" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle9 individualRectangleMinutes150" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle10 individualRectangleMinutes165" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle11 individualRectangleMinutes180" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle12 individualRectangleMinutes195" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle13 individualRectangleMinutes210" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle14 individualRectangleMinutes225" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle15 individualRectangleMinutes240" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle16 individualRectangleMinutes255" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle17 individualRectangleMinutes270" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle18 individualRectangleMinutes285" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle19 individualRectangleMinutes300" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle20 individualRectangleMinutes315" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle21 individualRectangleMinutes330" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle22 individualRectangleMinutes345" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle23 individualRectangleMinutes360" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle24 individualRectangleMinutes375" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle25 individualRectangleMinutes390" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle26 individualRectangleMinutes405" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle27 individualRectangleMinutes420" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle28 individualRectangleMinutes435" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle29 individualRectangleMinutes450" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle30 individualRectangleMinutes465" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle31 individualRectangleMinutes480" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle32 individualRectangleMinutes495" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle33 individualRectangleMinutes510" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle34 individualRectangleMinutes525" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle35 individualRectangleMinutes540" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle36 individualRectangleMinutes555" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle37 individualRectangleMinutes570" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle38 individualRectangleMinutes585" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle39 individualRectangleMinutes600" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle40 individualRectangleMinutes615" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle41 individualRectangleMinutes630" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle42 individualRectangleMinutes645" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle43 individualRectangleMinutes660" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle44 individualRectangleMinutes675" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle45 individualRectangleMinutes690" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle46 individualRectangleMinutes705" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle47 individualRectangleMinutes720" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle48 individualRectangleMinutes735" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle49 individualRectangleMinutes750" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle50 individualRectangleMinutes765" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle51 individualRectangleMinutes780" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle52 individualRectangleMinutes795" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle53 individualRectangleMinutes810" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle54 individualRectangleMinutes825" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle55 individualRectangleMinutes840" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle56 individualRectangleMinutes855" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle57 individualRectangleMinutes870" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle58 individualRectangleMinutes885" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle59 individualRectangleMinutes900" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle60 individualRectangleMinutes915" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle61 individualRectangleMinutes930" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle62 individualRectangleMinutes945" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle63 individualRectangleMinutes960" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle64 individualRectangleMinutes975" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle65 individualRectangleMinutes990" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle66 individualRectangleMinutes1005" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle67 individualRectangleMinutes1020" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle68 individualRectangleMinutes1035" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle69 individualRectangleMinutes1050" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle70 individualRectangleMinutes1065" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle71 individualRectangleMinutes1080" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle72 individualRectangleMinutes1095" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle73 individualRectangleMinutes1110" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle74 individualRectangleMinutes1125" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle75 individualRectangleMinutes1140" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle76 individualRectangleMinutes1155" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle77 individualRectangleMinutes1170" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle78 individualRectangleMinutes1185" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle79 individualRectangleMinutes1200" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle80 individualRectangleMinutes1215" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle81 individualRectangleMinutes1230" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle82 individualRectangleMinutes1245" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle83 individualRectangleMinutes1260" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle84 individualRectangleMinutes1275" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle85 individualRectangleMinutes1290" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle86 individualRectangleMinutes1305" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle87 individualRectangleMinutes1320" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle88 individualRectangleMinutes1335" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span><span class="individualRectangle individualRectangle89 individualRectangleMinutes1350" style="cursor: pointer; background-color: rgb(133, 169, 140); border: none;"></span>
                    <div></div>
                    <span class="individualRectangle individualRectangle90 individualRectangleMinutes1365" style="cursor: pointer;"></span><span class="individualRectangle individualRectangle91 individualRectangleMinutes1380" style="cursor: pointer;"></span><span class="individualRectangle individualRectangle92 individualRectangleMinutes1395" style="background-color: rgb(223, 201, 152); border: 3px solid rgb(173, 161, 135); box-shadow: 0px 0px 0px;"></span><span class="individualRectangle individualRectangle93 individualRectangleMinutes1410" style="background-color: rgb(223, 201, 152); border: 3px solid rgb(173, 161, 135); box-shadow: 0px 0px 0px;"></span><span class="individualRectangle individualRectangle94 individualRectangleMinutes1425" style="background-color: rgb(223, 201, 152); border: 3px solid rgb(173, 161, 135); box-shadow: 0px 0px 0px;"></span><span class="individualRectangle individualRectangle95 individualRectangleMinutes1440" style="background-color: rgb(223, 201, 152); border: 3px solid rgb(173, 161, 135); box-shadow: 0px 0px 0px;"></span>
                    <div class="RectanglesEndBlock" title="Click here to complete all available boxes" style="background-color: rgb(166, 141, 173);">90/96</div>
                </div>
            </div>

            <div id="rectangles_submenu" style="">
                <a href="#" title="Resets ALL your progress" id="resetprogress">Reset</a>
                <label class="switch" title="Automatically marks boxes as done when you hover your mouse over them">
                    <input type="checkbox" id="specialAbility">
                    <span class="slider round"></span>
                </label>
                <span title="Automatically marks boxes as done when you hover your mouse over them">Autoclick</span>
            </div>
        </div>
        <div id="rectangles_description_wrap">
            <h2>Habits</h2>
            <p>Each block represent a small part of your day.</p>
            <p>As the day goes on more blocks will be unlocked for you to click.</p>


            <p><span class="individualRectangle" style="background-color: rgb(223, 201, 152); border: 3px solid rgb(173, 161, 135); box-shadow: 0px 0px 0px;"></span><span style="height: 40px; display: inline-block; vertical-align: top; line-height: 40px;">This type of block is not avaible yet</span></p>
            <p><span class="individualRectangle" style="pointer-events: none;"></span><span style="height: 40px; display: inline-block; vertical-align: top; line-height: 40px;">This type of block can be clicked</span></p>
            <p>You can click the larger block to complete all avalible blocks for the selected date.</p>
            <p>You can select another date by clicking the date above the blocks.</p>
            <p>If you fail to follow your new habit you can click the reset button to start fresh</p>

        </div>




    </div>


</asp:Content>
